config/routes.rb
Rails.application.routes.draw do

  root "layouts#index"

  devise_for :users

  patch '/houses/:house_id/update', to: 'houses#update', as: 'house_update'
  patch '/payments/:payment_id/update', to: 'payments#update', as: 'payment_update'

  resources :charges
  resources :users, only: [:index, :show] 

  resources :houses, only: [:new, :create, :index, :show] do
    resources :payments, only: [:new, :create, :index], shallow: true
  end

end

app/models/house.rb
# == Schema Information
#
# Table name: houses
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class House < ActiveRecord::Base
  validates :name, presence: true

  has_many :payments
  has_many :users
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id         :integer          not null, primary key
#  name       :string
#  amount     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  house_id   :integer
#  category   :string
#

class Payment < ActiveRecord::Base
  validates :name, presence: true
  validates :amount, presence: true
  validates :house_id, presence: true
  validates :category, presence: true

  belongs_to :house
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  house_id               :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  
  belongs_to :house
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
  	@houses = House.all
  end

  def show
  	id = params[:id].to_i
  	@payments = Payment.where(house_id:id).all
  end

  def update
  	id = params[:house_id].to_i
    current_user.house = House.where(id:id).first
    current_user.save
    redirect_to "/"
  end

  def new
    @house = House.new
  end

  def create
    @house = House.create(house_params)
    if @house.save
      redirect_to houses_path
    else
      render "new"
    end
  end

  def house_params
    params.require(:house).permit(:name) #Returns a hash that was the value of "name" and "email" from the value of "user" in params.
  end

end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def index
    if current_user
        if current_user.house == nil
            redirect_to houses_path
        else
       
      		@house_id = current_user.house_id
        	house = Payment.where(house_id:@house_id).where(category:"house").all
        	bill = Payment.where(house_id:@house_id).where(category:"bill").all
        	grocery = Payment.where(house_id:@house_id).where(category:"grocery").all
        	etc = Payment.where(house_id:@house_id).where(category:"etc").all

        	@house_count = house.count
        	@bill_count = bill.count
        	@grocery_count = grocery.count
        	@etc_count = etc.count

        	@house_total = 0
        	@bill_total = 0
        	@grocery_total = 0
        	@etc_total = 0

        	house.each do |p|
        		@house_total += p.amount
        	end
        	
        	bill.each do |p|
        		@bill_total += p.amount
        	end

        	grocery.each do |p|
        		@grocery_total += p.amount
        	end

        	etc.each do |p|
        		@etc_total += p.amount
        	end

      		render "main"
        end
    else
    	render "index"
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  	@house = House.find params[:house_id]
  	@payment = @house.payments.build
  end

  def create
  	@house = House.find params[:house_id]
  	@payment = @house.payments.build payment_params
    @payment.paid = ""
  	if @payment.save
  		redirect_to house_payments_path(params[:house_id])
  	else
  		render "new"
    end
  end

  def index
    @house_id = params[:house_id]
    @house_name = House.where(id:@house_id).first.name
    @houses = Payment.where(house_id:@house_id).where(category:"house").all
    @bills = Payment.where(house_id:@house_id).where(category:"bill").all
    @grocerys = Payment.where(house_id:@house_id).where(category:"grocery").all
    @etcs = Payment.where(house_id:@house_id).where(category:"etc").all

    @house_total = 0
    @bill_total = 0
    @grocery_total = 0
    @etc_total = 0

    @houses.each do |p|
      @house_total += p.amount
    end
    
    @bills.each do |p|
      @bill_total += p.amount
    end

    @grocerys.each do |p|
      @grocery_total += p.amount
    end

    @etcs.each do |p|
      @etc_total += p.amount
    end

    render "index"
  end

  def update
    id = params[:payment_id]
    paid_list = Payment.where(id:id).first
    list = paid_list.paid
    if list == ""
      list.concat(current_user.name)
    else
      list.concat(", ")
      list.concat(current_user.name)
    end
    paid_list.save
    redirect_to :back
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, :category) #Returns a hash that was the value of "name" and "email" from the value of "user" in params.
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find params[:id]
  	@house = House.where(id:@user.house_id).first
  	@house_name = @house.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/houses/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Change House</title>

    <!-- Bootstrap Core CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Home</a>
            </div>
            <!-- /.navbar-header -->

            
            <!-- /.navbar-top-links -->

            
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><%= @house %></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>

            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Houses
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th> </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% count = 1 %>
                                        <% @houses.each do |house| %>
                                            <tr>
                                            <td> <%= count %> </td>
                                            <td> <%= house.name %> </td>
                                            <td> <%= link_to "Join", house_update_path(house.id), :method => :patch %> </td>
                                            </tr>
                                            <% count = count + 1 %>
                                        <% end %>
                                    </tbody>
                                </table>
                                <br>
                                <%= link_to 'Add New House', new_house_path, class: 'btn btn-lg btn-success btn-block' %>
                            </div>

                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                
            </div>
            

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>

</body>

</html>

app/views/houses/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>New House</title>

    <!-- Bootstrap Core CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">New House</h3>
                    </div>
                    <div class="panel-body">

                        	<%= form_for [@house] do |f| %>
							 	Name: <%= f.text_field :name %> <!-- Create a text field that sends its value under the key name-->
							 	<br> <br>
						    	<%= f.submit %> <!-- Create submit button-->
							<% end %>
                            
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js"></script>

</body>

</html>

app/views/houses/show.html.erb
<h1>Payment in House#show</h1>
<% @payments.each do |payment| %>
	<p> Name: <%= payment.name %> </p>
	<p> Category: <%= payment.category %> </p>
	<p> Amount: <%= payment.amount %> </p>
<% end %>
	

app/views/houses/update.html.erb
<%= params %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roommate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= current_user.name %></title>

    <!-- Bootstrap Core CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/dist/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><%= current_user.name %></a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><%= link_to 'User Profile', user_path(current_user.id) %>
                        </li>
                        <li class="divider"></li>
                        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %>

                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><%= current_user.house.name %></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @house_count %></div>
                                    <div>#house</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">Total: $<%= @house_total %></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @bill_count %></div>
                                    <div>#bill</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">Total: $<%= @bill_total %></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @grocery_count %></div>
                                    <div>#grocery</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">Total: $<%= @grocery_total %></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @etc_count %></div>
                                    <div>#etc</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">Total: $<%= @etc_total %></span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>

            </div>
            <br>
            <br>
            <div class="col-lg-3 col-md-4">
       		 </div>
            <div class="col-lg-3 col-md-4">
            	<%= link_to 'pay', house_payments_path(@house_id), class: 'btn btn-lg btn-success btn-block' %>
       		 </div>
       		 <div class="col-lg-3 col-md-4">
            	<%= link_to 'new', new_house_payment_path(@house_id), class: 'btn btn-lg btn-success btn-block' %>
       		 </div>

            <!-- /.row -->
           
                <!-- /.col-lg-8 -->
                
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/raphael/raphael-min.js"></script>
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/morrisjs/morris.min.js"></script>
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/js/morris-data.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js"></script>

</body>

</html>

app/views/payments/update.html.erb
<%= params %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<% @users.each do |users| %>
	<p> Name: <%= users.name %> </p>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title> User Profile </title>
		<link rel="stylesheet" href="https://jonglee.me/css/normalize.css">
		<link href='https://fonts.googleapis.com/css?family=Changa+One|Open+Sans:400italic,700italic,400,700,800' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://jonglee.me/css/main.css">
		<link rel="stylesheet" href="https://jonglee.me/css/responsive.css">

		<!-- MetisMenu CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="https://ironsummitmedia.github.io/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet">

		<meta name="viewport" content="width=    device-width, initial-scale=1.0">			
	</head>
	<body>
		<header>
			<a href="/" id="logo">
				<h1> <%= @user.name %> </h1>
			</a>
		</header>
		<div id="wrapper">
			<section>
				<img src="http://th03.deviantart.net/fs70/PRE/f/2012/080/c/2/coffee_in__code_out__by_mizuwebdesign-d4th7ky.jpg" alt="Photograph of Nick" class="profile-photo">
				<h3> Current House: <%= @house_name %> </h3>
				<a href="/houses"> Change House </a>
			</section>
			<footer>
				
				<p> &copy; JONG Y. LEE & DEYI YI </p>
			</footer>
		</div>
	</body>
</html>